[build-system]
requires = ["maturin>=1.5"]
build-backend = "maturin"

[project]
name = "rusty-cruncher"
version = "0.1.0"
description = "Rust-accelerated data rollups with Python bindings"
requires-python = ">=3.10"

[tool.maturin]
features = ["pyo3/extension-module"]
